version: '3'

services:

  ball_rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: 'ball_rabbitmq'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  ### Customer Management ###
  ball_customer_management_db:
    image: 'mongo'
    container_name: 'ball_customer_management_db'
    restart: on-failure
    ports:
      - '27011:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  ball_customer_management_service:
    build: CustomerManagementService/.
    container_name: 'ball_customer_management_service'
    restart: on-failure
    ports:
      - '8081:8080'
    environment:
      - MONGO_URL=mongodb://ball_customer_management_db:27017/app_development
      - MQ_URL=amqp://ball_rabbitmq:5672
    depends_on:
      - ball_rabbitmq
      - ball_customer_management_db

  ### Logistics Management ###
  ball_logistics_management_db:
    image: 'mongo'
    container_name: 'ball_logistics_management_db'
    ports:
      - '27012:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  ball_logistics_management_service:
    build: LogisticsManagementService/.
    container_name: 'ball_logistics_management_service'
    ports:
      - '8082:8080'
    environment:
      - MONGO_URL=mongodb://mongo:27012/app_development
    depends_on:
      - ball_rabbitmq
      - ball_logistics_management_db

  ### Notification ###
  ball_notification_db:
    image: 'mongo'
    container_name: 'ball_notification_db'
    ports:
      - '27013:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  ball_notification_service:
    build: NotificationService/.
    container_name: 'ball_notification_service'
    restart: on-failure
    ports:
      - '8083:8080'
    environment:
      - MONGO_URL=mongodb://ball_notification_db:27017/app_development
      - MQ_URL=amqp://ball_rabbitmq:5672
      - GMAIL_EMAIL=noreplyballcom@gmail.com
      - GMAIL_PASS=ybkhecuqaqxqspih
    depends_on:
      - ball_rabbitmq
      - ball_notification_db

  ### Order Management ###
  ball_order_management_db:
    image: 'mongo'
    container_name: 'ball_order_management_db'
    ports:
      - '27014:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  ball_order_management_service:
    build: OrderManagementService/.
    container_name: 'ball_order_management_service'
    ports:
      - '8084:8080'
    environment:
      - MONGO_URL=mongodb://mongo:27014/app_development
    depends_on:
      - ball_rabbitmq
      - ball_order_management_db

  ### Order Tracking ###
  ball_order_tracking_db:
    image: 'mongo'
    container_name: 'ball_order_tracking_db'
    ports:
      - '27015:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  ball_order_tracking_service:
    build: OrderTrackingService/.
    container_name: 'ball_order_tracking_service'
    ports:
      - '8085:8080'
    environment:
      - MONGO_URL=mongodb://mongo:27015/app_development
    depends_on:
      - ball_rabbitmq
      - ball_order_tracking_db

  ### Payment ###
  ball_payment_db:
    image: 'mongo'
    container_name: 'ball_payment_db'
    ports:
      - '27016:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  ball_payment_service:
    build: PaymentService/.
    container_name: 'ball_payment_service'
    ports:
      - '8086:8080'
    environment:
      - MONGO_URL=mongodb://mongo:27016/app_development
    depends_on:
      - ball_rabbitmq
      - ball_payment_db

  ### Product Management ###
  ball_product_management_db:
    image: 'mongo'
    container_name: 'ball_product_management_db'
    ports:
      - '27017:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  ball_product_management_service:
    build: ProductManagementService/.
    container_name: 'ball_product_management_service'
    ports:
      - '8087:8080'
    environment:
      - MONGO_URL=mongodb://ball_product_management_db:27017/app_development
      - MQ_URL=amqp://ball_rabbitmq:5672
    depends_on:
      - ball_rabbitmq
      - ball_product_management_db

  ### Service Department ###
  ball_service_department_db:
    image: 'mongo'
    container_name: 'ball_service_department_db'
    ports:
      - '27018:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  ball_service_department_service:
    build: ServiceDepartmentService/.
    container_name: 'ball_service_department_service'
    ports:
      - '8088:8080'
    environment:
      - MONGO_URL=mongodb://mongo:27018/app_development
    depends_on:
      - ball_rabbitmq
      - ball_service_department_db

  ### Supplier Management ###
  ball_supplier_management_db:
    image: 'mongo'
    container_name: 'ball_supplier_management_db'
    ports:
      - '27019:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  ball_supplier_management_service:
    build: SupplierManagementService/.
    container_name: 'ball_supplier_management_service'
    ports:
      - '8089:8080'
    environment:
      - MONGO_URL=mongodb://ball_supplier_management_db:27017/app_development
      - MQ_URL=amqp://ball_rabbitmq:5672
    depends_on:
      - ball_rabbitmq
      - ball_supplier_management_db
